"""QlikSense exporter — master items JSON + QVS load script."""

from __future__ import annotations
import json
from collections import defaultdict
from kelpmesh.semantic.exporters.base import BaseExporter, ExportResult


_QLIK_AGG = {
    "count": "Count",
    "count_distinct": "Count(Distinct",
    "sum": "Sum",
    "average": "Avg",
    "min": "Min",
    "max": "Max",
}


class QlikExporter(BaseExporter):
    """Generates master items JSON and a QVS LOAD script for QlikSense."""

    format = "qlik"

    def export(self) -> ExportResult:
        by_model: dict[str, list] = defaultdict(list)
        for m in self.metrics:
            by_model[m.model or "kelpmesh_metrics"].append(m)

        all_measures: list[dict] = []
        all_dimensions: list[dict] = []
        qvs_lines: list[str] = [
            "// QlikSense Load Script generated by kelpmesh semantic layer",
            "",
        ]

        seen_dims: set[str] = set()

        for model_name, metrics in by_model.items():
            qvs_lines += self._load_block(model_name, metrics)

            for m in metrics:
                all_measures.append(self._measure_item(m, model_name))
                for dim in m.dimensions:
                    if dim not in seen_dims:
                        seen_dims.add(dim)
                        all_dimensions.append(self._dimension_item(dim, model_name))

        master_items = {
            "measures": all_measures,
            "dimensions": all_dimensions,
        }

        return ExportResult(
            files={
                "master_items.json": json.dumps(master_items, indent=2),
                "load_script.qvs": "\n".join(qvs_lines),
            },
            format=self.format,
        )

    def _measure_item(self, m, model_name: str) -> dict:
        item: dict = {
            "qInfo": {"qType": "measure"},
            "qMeasure": {
                "qLabel": self._label(m),
                "qDef": self._qlik_expression(m, model_name),
                "qGrouping": "N",
            },
            "qMetaDef": {
                "title": self._label(m),
                "description": self._description(m),
                "tags": m.tags,
            },
        }
        if m.format_string:
            item["qMeasure"]["qNumFormat"] = {
                "qType": "F",
                "qFmt": m.format_string,
            }
        return item

    def _dimension_item(self, dim: str, model_name: str) -> dict:
        return {
            "qInfo": {"qType": "dimension"},
            "qDim": {
                "qFieldDefs": [f"[{model_name}].{dim}"],
                "qFieldLabels": [dim.replace("_", " ").title()],
                "qGrouping": "N",
            },
            "qMetaDef": {
                "title": dim.replace("_", " ").title(),
            },
        }

    def _qlik_expression(self, m, model_name: str) -> str:
        col = m.sql or m.name
        if m.type == "count":
            return f"Count([{model_name}])"
        elif m.type == "count_distinct" and m.sql:
            return f"Count(Distinct [{col}])"
        elif m.type in ("sum", "average", "min", "max") and m.sql:
            fn = _QLIK_AGG[m.type]
            return f"{fn}([{col}])"
        elif m.type == "expression" and m.sql:
            return m.sql
        elif m.type == "ratio" and m.numerator and m.denominator:
            return (
                f"Sum([{m.numerator}]) / "
                f"If(Sum([{m.denominator}]) = 0, Null(), Sum([{m.denominator}]))"
            )
        elif m.type == "derived" and m.expression:
            expr = m.expression
            for other in self.metrics:
                expr = expr.replace(f"{{{{{other.name}}}}}", f"$(={self._label(other)})")
            return expr
        return f"Count([{model_name}])"

    def _load_block(self, model_name: str, metrics: list) -> list[str]:
        dims = self._collect_dimensions(metrics)
        cols = dims + [m.sql or m.name for m in metrics if m.sql or m.name]
        cols = list(dict.fromkeys(cols))
        col_list = ",\n    ".join(cols) if cols else "*"
        return [
            f"[{model_name}]:",
            f"LOAD",
            f"    {col_list}",
            f"FROM [lib://DataFiles/{model_name}.qvd] (qvd);",
            "",
        ]

    def _collect_dimensions(self, metrics: list) -> list[str]:
        seen: set[str] = set()
        dims: list[str] = []
        for m in metrics:
            for d in m.dimensions:
                if d not in seen:
                    seen.add(d)
                    dims.append(d)
        return dims
